name = "ExBroadcast"
uuid = "fffd924a-3fb1-4301-8d96-27f352b59164"
version = "0.1.0"
authors = ["N5N3"]

[deps]
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[extensions]
ExBroadcastAdaptExt = "Adapt"
ExBroadcastGPUArraysCoreExt = ["GPUArraysCore", "KernelAbstractions"]
ExBroadcastOffsetArraysExt = "OffsetArrays"
ExBroadcastStaticArraysExt = "StaticArrays"
ExBroadcastStructArraysExt = "StructArrays"

[compat]
PrecompileTools = "1.3.3"
GPUArraysCore = "0.2"
KernelAbstractions = "0.9"
julia = "1.11"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StructArrays", "OffsetArrays", "StaticArrays"]
